/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import dao.UsuarioDAO;
import javax.swing.JFrame;
import java.awt.Container;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
/**
 *
 * @author stephanie
 */
public class ListaGUI extends javax.swing.JFrame {
   DefaultTableModel model = new DefaultTableModel();
   Container cnt = this.getContentPane();
   JTable jtbl = new JTable(model);
    public ListaGUI() {
        cnt.setLayout(new FlowLayout(FlowLayout.LEFT));
        model.addColumn("ID");
        model.addColumn("Nome");
        model.addColumn("CPF");
        model.addColumn("E-mail");
        model.addColumn("Telefone");
        try {
            UsuarioDAO dao = new UsuarioDAO();
            Object[] rowData = new Object[5];
            ArrayList<Usuario> listaDeUsuarios = new ArrayList<>();
            listaDeUsuarios = dao.listarUsuarios();
        for(int i = 0; i < listaDeUsuarios.size(); i++){
            rowData[0] = listaDeUsuarios.get(i).getId();
            rowData[1] = listaDeUsuarios.get(i).getNome();
            rowData[2] = listaDeUsuarios.get(i).getCpf();
            rowData[3] = listaDeUsuarios.get(i).getEmail();
            rowData[4] = listaDeUsuarios.get(i).getTelefone();
            model.addRow(rowData);
        }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        JScrollPane pg = new JScrollPane(jtbl);
        cnt.add(pg);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       JFrame frame = new ListaGUI();
        frame.setTitle("Lista de Usuários");
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
}
